### ISSUE TITLE
Links are too dark

### ISSUE THREAD

**Issue by nnblack1980** [Esri/calcite-bootstrap#206]
This is a known issue that I've talked to @julio8a about.

We're currently using Calcite-Blue-a250 for <a> links and they don't stand out very well, especially when they are part of a larger span of text.

Suggest lightening to Calcite-Highlight-Blue-350

**Comment by nnblack1980** [comment]
Should this also be considered for other areas we're using the a250 color- like buttons?

**Comment by kyle-03674** [comment]
Using Calcite-Highlight-Blue-350 might work. It still passes AA contrast check, and is noticeably different from black. @nnblack1980 can you show me some example uses with the new color? I would want to be sure the lighter color works in all situations.

**Comment by kyle-03674** [comment]
@bstifle  I know you looked into button colors many months ago, and I have a feeling you were involved with link colors at that time. Do you see a problem changing link color in calcite bootstrap to Calcite-Highlight-Blue-350 instead of Calcite-Blue-a250.

**Comment by bstifle** [comment]
@kyle-03674 

#007ac2 correct? That's fine with me, i thought we were already doing that. I've been using that in my latest designs.

**Comment by kyle-03674** [comment]
yes, #007ac2

**Comment by julio8a** [comment]
Thanks @kyle-03674 and @bstifle 

@nnblack1980 I'll work with @TheBlueDog on this.

**Comment by nnblack1980** [comment]
Just catching up on this. Thanks guys.

**Comment by TheBlueDog** [comment]
Thanks for bringing this back up.

Currently in the variables we set `$brand-primary` variable value to `$Calcite_Blue_a250`. Link colors use the value of `$brand-primary` as well as primary-buttons. The color we are using for link hover states is `$Calcite_Highlight_Blue_400` and I'm assuming we don't want to change that.

I'll update the variables so that `$brand-primary` uses `$Calcite-Highlight-Blue-350`

The color we are using for link hover states is `$Calcite_Highlight_Blue_400` and I'm assuming we don't want to change that.

**Comment by kyle-03674** [comment]
i think the hover state is fine as-is.

**Comment by TheBlueDog** [comment]
Decided to only change the variable for `$link-color` as changing the `$brand-primary` will ripple through the buttons and many other places.

New color links ($Calcite-Highlight-Blue-350):
![screen shot 2016-02-19 at 8 09 45 am](https://cloud.githubusercontent.com/assets/5419306/13176427/32e1e760-d6e0-11e5-88c8-c502f3cb97a9.png)

Original color links ($Calcite_Blue_a250):
![screen shot 2016-02-19 at 8 10 02 am](https://cloud.githubusercontent.com/assets/5419306/13176431/3f51eb9e-d6e0-11e5-9c44-d51d6ab630a7.png)

**Comment by TheBlueDog** [comment]
I ran this change by @FelFly for accessibility check. She said the issue is #f8f8f8 is our standard page background, and in order for the new color to pass, all links would need to be bold.

![screen_shot_2016-02-19_at_8 15 56_am](https://cloud.githubusercontent.com/assets/5419306/13176754/789dc9ac-d6e2-11e5-8106-bbdb5fe7c4ea.png)

She did solve the problem on Open Data by finding the closest match that would pass, which is `$Calcite_Highlight_Blue_250` (#136fbf) from the dark palette.

![screen_shot_2016-02-19_at_8 17 12_am](https://cloud.githubusercontent.com/assets/5419306/13176764/82a5899e-d6e2-11e5-89d1-c50eb74b8ab7.png)

If we have `$Calcite_Blue_a250` as our overall branding ESRI Blue, what do you think about having a new variable `$Calcite_Blue_t250` (t for text) that is the text link color? (I've edited the comment above to include this color as an option.)

@kyle-03674

**Comment by kyle-03674** [comment]
@TheBlueDog @FelFly  nice work. Thanks for the 3 examples.  I had run accessbility check yesterday, but used white background. With #f8f8f8 I can see why Calcite Blue 350 would not work well enough. I support your call to use the dark swatch Calcite Highlight Blue 250. It's saturated enough to stand out from text, and dark enough to pass accessibility on that background.

Regarding *naming* I'm going to look after my next meeting, and propose a new color name, using the value of #136fbf, with a name like Calcite Highlight Blue 325 or 375, for both dark and light palettes. I don't want to make a whole new set for text.

Gotta run for now...

**Comment by kyle-03674** [comment]
The name for #136fbf would be Calcite_Highlight_Blue_360. It looks like the attached, when compared with other colors. Note, the accessibility notes on the attached are based on pure white and black backgrounds, which aren't specific to any particular project.
![image](https://cloud.githubusercontent.com/assets/11050471/13188793/7df18d0a-d708-11e5-982f-be0542284c70.png)

I won't be able to update the Patterns repo with the added color until later next week.

**Comment by nnblack1980** [comment]
Are we assuming the link background is always going to have a background color of #f8f8f8?

**Comment by TheBlueDog** [comment]
> Are we assuming the link background is always going to have a background color of #f8f8f8?

That's what the default page body background color is. Not to say someone couldn't customize it, but I believe that's the 'style.'

**Comment by nnblack1980** [comment]
Could we make the default background color white?

**Comment by TheBlueDog** [comment]
Paging @CassidyB ^^

**Comment by nnblack1980** [comment]
Aside from the background contrast, we should consider colors used for links elsewhere on the web. Links should be vibrant and noticeable- I feel like we're missing the mark with the chosen color. 

In workforce we use white background for a lot of our content- and the dark blue is not working well. The links look dull and don't stand out at all- especially went surrounded by other text.

**Comment by CassidyB** [comment]
As we start to review Calcite Web and the Bootstrap implementation over the next few months we will be making sure that we take another hard look at the designs based on feedback collected over the last year.  

Items that we will look at will include color.  In regards to using white as a background color.
