### ISSUE TITLE
404 http://esri.github.io/calcite-bootstrap/assets/css/calcite-bootstrap.css

### ISSUE THREAD

**Issue by umacgillivray** [Esri/calcite-bootstrap#294]
@dbouwman @FelFly 
Does anyone know what happened to this?
 
http://esri.github.io/calcite-bootstrap/assets/css/calcite-bootstrap.css

I have some apps that are pointing to it, but it's now a 404.

**Comment by dbouwman** [comment]
@umacgillivray sorry about that - we are going to re-build the calcite-bootstrap docs site, but during the re-vamping of the actual css/sass, we found that this repo was in a really O_o state so we had to kill the gh-pages branch.

I'm sorry that you were using the gh-pages site as a CDN and all I can say is that we are aware that a doc site is needed. But - even when that's up, it's not a good idea to depend on a gh-pages site as a CDN - we also plan to get this up on an official Esri CDN at some point.

For now though - I'd recommend simply `npm i calcite-bootstrap` and then adding the css file into your projects /styles or /css folder and hosting it inside the app.

Also note that the new version actually adheres do Calcite - so you may see some (minor) changes to your apps. If you need the older version you can install a specific version using `npm i calcite-bootstrap@0.3.4` which was the last of the old versions.

**Comment by FelFly** [comment]
Yes, my apologies. I was given responsibility to maintain this project and to make it into an actual theme. The goal being that developers could choose to use the Calcite Bootstrap theme, but in a manner that would also allow support of AGO's customer shared theme resources should that need to be layered on afterward, and then to have both of those themes paint over default Bootstrap. However, the gh-pages link was documentation for the old instance of the project that had a redundant full instance of Bootstrap running, and I really need the link in order to document the new theme, so I had asked my manager for help in getting access and he helped me reset it yesterday.

Dave has good advice for either maintaining your older instance or upgrading to the new theme and hosting your CSS. The theme + expansions CSS should give any app using Bootstrap 3 a fully Calcite Web look. I'm still ironing out a few kinks, but we're almost there.

**Comment by dbouwman** [comment]
@umacgillivray if you need to get something working again "now", we have a new doc site up, and you *can* use this url - but this is the 0.4.x version, which has changed things...

`http://esri.github.io/calcite-bootstrap/styles/calcite-bootstrap.min.css`

That file will always be the latest - including alpha/beta versions, and may/may-not have horrifying breaking changes. So it's always best to pull a version into your app. @FelFly will be updating the docs in the coming days

**Comment by KathleenPate** [comment]
Thanks for your work on this. My site blew up today and I'm glad I have a temporary fix.

**Comment by umacgillivray** [comment]
@dbouwman @FelFly 
Thanks. From here on we will include the files within our app. In the short term, we have some copies out there that will be broken. Is it possible to put some content at http://esri.github.io/calcite-bootstrap/assets/css ? I can provide the files.

**Comment by dbouwman** [comment]
@umacgillivray can you make a PR to this repo w/ the files?

**Comment by umacgillivray** [comment]
@dbouwman 
Ok. Where will I put them: Esri/calcite-bootstrap/docs/assets ?

**Comment by dbouwman** [comment]
@umacgillivray yep!

if you can name them something specific to indicate you are using them that would be ideal. Or - even better - put them in a sub-folder, like `/v0.3.2/` that would be great - I just don't want to inadvertently delete them on you.

Once you've converted your apps, make another PR to this repo that removes the files.

**Comment by umacgillivray** [comment]
@dbouwman I don't have write access to this repo. I'll try Fork.

**Comment by dbouwman** [comment]
@umacgillivray yeah - fork and PR back is the flow for public repos :)

**Comment by umacgillivray** [comment]
@dbouwman PR https://github.com/Esri/calcite-bootstrap/pull/295

**Comment by dbouwman** [comment]
@umacgillivray merged

**Comment by umacgillivray** [comment]
@dbouwman @FelFly 
Thanks!
